### ISSUE TITLE
Requests returning XML

### ISSUE THREAD

**Issue by derwehr** [kaefer3000/t2-rest-leds-sosa#1]
I installed everything as described in your readme, on node version 6.14.4. Tried lts and latest too, but when i send a get request to the app it always returns in the following format (sent to the root of the app):

```
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about="#tessel2">
        <ns58728:type xmlns:ns58728="http://www.w3.org/1999/02/22-rdf-syntax-ns#" rdf:resource="http://www.w3.org/ns/sosa/Platform"/>
    </rdf:Description>
    <rdf:Description rdf:about="#tessel2">
        <ns26523:isPrimaryTopicOf xmlns:ns26523="http://xmlns.com/foaf/0.1/" rdf:resource=""/>
    </rdf:Description>
    <rdf:Description rdf:about="#tessel2">
        <ns8688:hosts xmlns:ns8688="http://www.w3.org/ns/sosa/" rdf:resource="leds/#bar"/>
    </rdf:Description>
    <rdf:Description rdf:about="#tessel2">
        <ns55125:hosts xmlns:ns55125="http://www.w3.org/ns/sosa/" rdf:resource="leds/systems/#sensact"/>
    </rdf:Description>
</rdf:RDF>
```

**Comment by kaefer3000** [comment]
Hi,

that's RDF serialised in XML according to the RDF/XML specification. Using the mechanism of content-negotiation, you should be able to obtain RDF in other, better readable formats (eg. JSON-LD or Turtle). Can you be more specific in what you tried and expect?

Cheers!

**Comment by derwehr** [comment]
Hi,
thanks for the quick answer. Here's what I did:
I installed the app as follows:

```
git clone https://github.com/kaefer3000/t2-rest-leds-sosa/
cd t2-rest-leds-sosa,
npm install
t2 rename t2-rest-leds
t2 push .
```

Then i send a request to the app via:
`curl http://localhost/`

I expected to get an answer in the format you described in your readme:

```
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix sosa: <http://www.w3.org/ns/sosa/> .

<#tessel2>
  a sosa:Platform ;
  foaf:isPrimaryTopicOf <> ;
  sosa:hosts <leds/#bar> .
  sosa:hosts <leds/systems/#sensact> .
```
instead I got RDF/XML.

How would I go about getting the expected output?

**Comment by kaefer3000** [comment]
Short answer: `curl -Haccept:text/turtle http://localhost/`.

Explanation: This way, you tell curl to explicitly request Turtle (the format you desire) from the server. Per default, curl requests the server to send "whatever format the server likes", in which case the server framework picks a format from the formats available. Seems like the default format is RDF/XML in your case for whatever reason (maybe there is some randomness involved if there is no explicit request for certain formats).

**Comment by derwehr** [comment]
Thank you! Everything's working as intended now.
